POST  http://localhost:3000/users/register
Content-Type: application/json

{
    "name":"rapidd",
    "email":"grasd@gmail.com",
    "password":"sample@1234"
}

###

POST  http://localhost:3000/users/login
Content-Type: application/json

{
    "email":"rapid@gmail.com",
    "password":"sample@1234"
}


###

GET  http://localhost:3000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY5NTllNzAwZmQ2NzI0NGM4OGRiZWIiLCJpYXQiOjE2MTc1Mzk4OTN9.WesH3m69nVIbPWFKgdFpljcGjrZfq9xJbzQZnHVrExs

###

POST http://localhost:3000/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY5NDVhMWM2ODc4MjQxNmMwNWRmN2YiLCJpYXQiOjE2MTc1MTYxNzB9.J7EHFHzsBzCPsyrXn8W0giuZkjBmU7X3RvJrpkm632U

###

POST http://localhost:3000/users/logoutall
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY5NTllNzAwZmQ2NzI0NGM4OGRiZWIiLCJpYXQiOjE2MTc1Mzk4OTN9.WesH3m69nVIbPWFKgdFpljcGjrZfq9xJbzQZnHVrExs