POST  http://localhost:3000/users/register
Content-Type: application/json

{
    "name":"rapid",
    "email":"rapid@gmail.com",
    "password":"sample@1234"
}

###

POST  http://localhost:3000/users/login
Content-Type: application/json

{
    "email":"rapid@gmail.com",
    "password":"sample@1234"
}


###

GET  http://localhost:3000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY5NTllNzAwZmQ2NzI0NGM4OGRiZWIiLCJpYXQiOjE2MTc1MTcwMzF9.NQI1i3-vkQvEB_4EmwdSG7uKYMsM_cUXQNKO_WhsDFI

###

POST http://localhost:3000/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY5NDVhMWM2ODc4MjQxNmMwNWRmN2YiLCJpYXQiOjE2MTc1MTYxNzB9.J7EHFHzsBzCPsyrXn8W0giuZkjBmU7X3RvJrpkm632U

###

POST http://localhost:3000/users/logoutall
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY5NDVhMWM2ODc4MjQxNmMwNWRmN2YiLCJpYXQiOjE2MTc1MTY5NDJ9.lLApcm4PWixv1IMfmeUAUlVwaItE6mqUFZBQtEZ2YWQ