GET http://localhost:5000/api/post/
Accept: application/json

###

GET http://localhost:3000/api/post/6069638e86bfa90944125610

###

POST http://localhost:5000/api/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDZhZTQ2N2NlNWQ5NzJmZTQ2OWI4M2YiLCJpYXQiOjE2MTc2Mjg5NzV9.Ny9P-lpo51MIOORgFqYHPCLFADXQni2DJLwfxIBKRr0

{
    "title": "yellow screen",
    "author": "Rapido steven",
    "description": "Picture from sky divers",
    "imageUrl": "https://images.unsplash.com/photo-1448375240586-882707db888b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"
}

###
                
DELETE http://localhost:3000/api/post/6069638e86bfa90944125610
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY5NTllNzAwZmQ2NzI0NGM4OGRiZWIiLCJpYXQiOjE2MTc1MTcwMzF9.NQI1i3-vkQvEB_4EmwdSG7uKYMsM_cUXQNKO_WhsDFI

###

PUT http://localhost:5000/api/post/606af7c4d70b5f510844117a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDZhZTQ2N2NlNWQ5NzJmZTQ2OWI4M2YiLCJpYXQiOjE2MTc2Mjg5NzV9.Ny9P-lpo51MIOORgFqYHPCLFADXQni2DJLwfxIBKRr0

{
    "title": "Amazing videography",
    "description": "Picture is taken from mangoorve forest",
    "imageUrl": "https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?ixid=MXwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEzfHx8ZW58MHx8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60"
}

###

POST http://localhost:3000/api/post/606963c186bfa90944125611/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY5NTllNzAwZmQ2NzI0NGM4OGRiZWIiLCJpYXQiOjE2MTc1MTcwMzF9.NQI1i3-vkQvEB_4EmwdSG7uKYMsM_cUXQNKO_WhsDFI

{   
    "author": "Steven rapido",
    "content": "It looks scary"
}