GET http://localhost:3000/api/post

###

GET http://localhost:3000/api/post/6068b96062cfcc206c4237d1

###

POST http://localhost:3000/api/post
Content-Type: application/json

{
    "title": "Amazing photography",
    "author": "Vadivazhagan",
    "description": "Picture is taken from amazon forest",
    "imageUrl": "https://images.unsplash.com/photo-1448375240586-882707db888b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"
}

###

DELETE http://localhost:3000/api/post/6068ba53f0a81348406d4c83

###

PATCH http://localhost:3000/api/post/606943910777a94ec0390b14
Content-Type: application/json

{
    "title": "Amazing videography",
    "description": "Picture is taken from mangoorve forest",
    "imageUrl": "https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?ixid=MXwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEzfHx8ZW58MHx8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60"
}