export const individualPostTypes = {
  FETCH_INDIVIDUAL_POST_START: "FETCH_INDIVIDUAL_POST_START",
  FETCH_INDIVIDUAL_POST_SUCCESS: "FETCH_INDIVIDUAL_POST_SUCCESS",
  FETCH_INDIVIDUAL_POST_FAILURE: "FETCH_INDIVIDUAL_POST_FAILURE",
  CLEAR_POST_STATE:"CLEAR_POST_STATE"
};
