export const userTypes = {
    USER_SIGN_IN_START:"USER_SIGN_IN_START",
    USER_SIGN_IN_SUCCESS:"USER_SIGN_IN_SUCCESS",
    USER_SIGN_IN_FAILURE:"USER_SIGN_IN_FAILURE",
    USER_SIGN_REGISTER_START:"USER_SIGN_REGISTER_START",
    USER_SIGN_REGISTER_SUCCESS:"USER_SIGN_REGISTER_SUCCESS",
    USER_SIGN_REGISTER_FAILURE:"USER_SIGN_REGISTER_FAILURE",
    USER_SIGN_OUT_START:"USER_SIGN_OUT_START",
    USER_SIGN_OUT_SUCCESS:"USER_SIGN_OUT_SUCCESS",
    USER_SIGN_OUT_FAILURE:"USER_SIGN_OUT_FAILURE"
}